### ISSUE TITLE
Inspector breaks on elements with `url()` background-image values

### ISSUE THREAD

**Issue by gilmoreorless** [rafaelcaricio/gradient-inspector#15]
Gradient Inspector delegates to Gradient Parser for getting gradient values, but Gradient Parser _only_ handles gradient values.

If I have an element with multiple backgrounds, and one of them is a non-gradient image, Gradient Inspector fails to render the backgrounds due to an error thrown by Gradient Parser.

Example in code form:

```css
.this-works {
  background-image: linear-gradient(...), linear-gradient(...);
}

.this-breaks {
  background-image: url(http://...), linear-gradient(...);
}
```
